export const UserActionTypes = {
    FETCH_CURRENT_USER: 'FETCH_CURRENT_USER',
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    FETCH_USER_FAILURE: 'FETCH_USER_FAILURE',
    USER_LOGOUT: 'USER_LOGOUT',
};
